In [1]:
from dotenv import load_dotenv
import sys
import os
from kiteconnect import KiteConnect
from datetime import datetime, timedelta
import time
import pandas as pd
from pathlib import Path
sys.path.append(os.path.abspath(""))
load_dotenv()

True

In [7]:
pwd

'D:\\Study\\Programs\\trading'

In [8]:
# Get Access token
with open(os.path.join("assets", "loginInfo", "access_token.txt"), 'r', encoding='utf-8') as file:
    access_token = file.read()

In [9]:
# PARAMETERS

instrument_token = 256265  # NIFTY
file_name = "nifty_1min_full.json"
target_date = '2026-04-16' #should be N


start_date = datetime(2020, 1, 1)
date_obj = datetime.strptime(target_date, '%Y-%m-%d')
formatted_date = date_obj.strftime("%d%b%Y").upper()
next_day_obj = date_obj + timedelta(days=1)
end_date = datetime(next_day_obj.year, next_day_obj.month, next_day_obj.day) # If N is your target date, then put N+1
delta = timedelta(days=60)

In [11]:
kite = KiteConnect(api_key=os.getenv('KITE_API_KEY'),)
kite.set_access_token(access_token)

while start_date < end_date:
    chunk_end = min(start_date + delta, end_date)

    print(f"Fetching: {start_date} → {chunk_end}")

    for attempt in range(3):
        try:
            data = kite.historical_data(
                instrument_token=instrument_token,
                from_date=start_date,
                to_date=chunk_end,
                interval="minute"
            )
            break
        except Exception as e:
            print("Retrying...", e)
            time.sleep(1)

    df = pd.DataFrame(data)
    # path = Path("D:/Study/Programs/trading/assets/historical") / file_name
    # df.to_csv(
    #     path,
    #     mode='a',
    #     header=not path.exists(),
    #     index=False
    # )

    path = Path("assets/historical") / f"{file_name}"

    df.to_json(
        path,
        orient="records",
        lines=True,
        mode="a")

    time.sleep(0.4)
    start_date = chunk_end + timedelta(seconds=1)

print("Download complete")

Fetching: 2020-01-01 00:00:00 → 2020-03-01 00:00:00

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2020-03-01 00:00:01 → 2020-04-30 00:00:01

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2020-04-30 00:00:02 → 2020-06-29 00:00:02

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2020-06-29 00:00:03 → 2020-08-28 00:00:03

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2020-08-28 00:00:04 → 2020-10-27 00:00:04

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2020-10-27 00:00:05 → 2020-12-26 00:00:05

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2020-12-26 00:00:06 → 2021-02-24 00:00:06

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2021-02-24 00:00:07 → 2021-04-25 00:00:07

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2021-04-25 00:00:08 → 2021-06-24 00:00:08

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2021-06-24 00:00:09 → 2021-08-23 00:00:09

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2021-08-23 00:00:10 → 2021-10-22 00:00:10

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2021-10-22 00:00:11 → 2021-12-21 00:00:11

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2021-12-21 00:00:12 → 2022-02-19 00:00:12

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2022-02-19 00:00:13 → 2022-04-20 00:00:13

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2022-04-20 00:00:14 → 2022-06-19 00:00:14

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2022-06-19 00:00:15 → 2022-08-18 00:00:15

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2022-08-18 00:00:16 → 2022-10-17 00:00:16

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2022-10-17 00:00:17 → 2022-12-16 00:00:17

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2022-12-16 00:00:18 → 2023-02-14 00:00:18

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2023-02-14 00:00:19 → 2023-04-15 00:00:19

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2023-04-15 00:00:20 → 2023-06-14 00:00:20

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2023-06-14 00:00:21 → 2023-08-13 00:00:21

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2023-08-13 00:00:22 → 2023-10-12 00:00:22

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2023-10-12 00:00:23 → 2023-12-11 00:00:23

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2023-12-11 00:00:24 → 2024-02-09 00:00:24

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2024-02-09 00:00:25 → 2024-04-09 00:00:25

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2024-04-09 00:00:26 → 2024-06-08 00:00:26

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2024-06-08 00:00:27 → 2024-08-07 00:00:27

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2024-08-07 00:00:28 → 2024-10-06 00:00:28

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2024-10-06 00:00:29 → 2024-12-05 00:00:29

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2024-12-05 00:00:30 → 2025-02-03 00:00:30

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2025-02-03 00:00:31 → 2025-04-04 00:00:31

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2025-04-04 00:00:32 → 2025-06-03 00:00:32

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2025-06-03 00:00:33 → 2025-08-02 00:00:33

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2025-08-02 00:00:34 → 2025-10-01 00:00:34

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2025-10-01 00:00:35 → 2025-11-30 00:00:35

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2025-11-30 00:00:36 → 2026-01-29 00:00:36

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2026-01-29 00:00:37 → 2026-03-30 00:00:37

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Fetching: 2026-03-30 00:00:38 → 2026-04-17 00:00:00

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1147230474.py:33: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json(

Download complete

##

In [20]:
file_name

'nifty_1min_full.json'

In [22]:
file_path = Path(f"assets/historical/{file_name}")
nifty_all = pd.read_json(file_path, lines=True)

In [23]:
nifty_all.tail()

                       date      open      high       low     close  volume
1743508 2026-04-16 09:55:00  24196.10  24199.95  24189.20  24193.15       0
1743509 2026-04-16 09:56:00  24193.15  24196.65  24190.10  24194.05       0
1743510 2026-04-16 09:57:00  24194.05  24195.40  24191.00  24192.80       0
1743511 2026-04-16 09:58:00  24192.80  24194.70  24185.15  24187.50       0
1743512 2026-04-16 09:59:00  24187.50  24190.45  24178.85  24188.40       0

In [24]:
nifty_all.iloc[0]["date"]

Timestamp('2020-01-01 03:45:00')

In [25]:
import pandas as pd
import json

def parse_date(x):
    try:
        if isinstance(x, dict):
            return x['date']
        if isinstance(x, str):
            return json.loads(x.rstrip('}') + '}')['date']
        return x
    except:
        return None

nifty_all['date'] = (
    pd.to_datetime(nifty_all['date'].map(parse_date), unit='ms', errors='coerce', utc=True)
    .dt.tz_convert('Asia/Kolkata')
)

day_df = nifty_all.loc[
    nifty_all['date'].dt.date == pd.to_datetime(date_obj).date()
]

In [26]:
day_df

,date,open,high,low,close,volume
1160092,2026-04-16 09:15:00+05:30,24385.20,24392.35,24333.95,24355.15,0
1160093,2026-04-16 09:16:00+05:30,24353.50,24367.60,24341.90,24360.40,0
1160094,2026-04-16 09:17:00+05:30,24360.90,24381.10,24360.90,24380.35,0
1160095,2026-04-16 09:18:00+05:30,24379.25,24379.25,24364.60,24376.20,0
1160096,2026-04-16 09:19:00+05:30,24373.05,24390.55,24373.05,24390.55,0
...,...,...,...,...,...,...
1743508,2026-04-16 15:25:00+05:30,24196.10,24199.95,24189.20,24193.15,0
1743509,2026-04-16 15:26:00+05:30,24193.15,24196.65,24190.10,24194.05,0
1743510,2026-04-16 15:27:00+05:30,24194.05,24195.40,24191.00,24192.80,0
1743511,2026-04-16 15:28:00+05:30,24192.80,24194.70,24185.15,24187.50,0
1743512,2026-04-16 15:29:00+05:30,24187.50,24190.45,24178.85,24188.40,0

In [28]:
formatted_date

'16APR2026'

In [36]:
file_path = Path(f"assets/logs/{formatted_date}") / f"nifty_1min_{formatted_date}.json"
day_df.to_json(file_path, orient="records", lines=True)

C:\Users\bhatt\AppData\Local\Temp\ipykernel_63032\1991447199.py:2: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  day_df.to_json(file_path, orient="records", lines=True)

In [37]:
day_df

,date,open,high,low,close,volume
1160092,2026-04-16 09:15:00+05:30,24385.20,24392.35,24333.95,24355.15,0
1160093,2026-04-16 09:16:00+05:30,24353.50,24367.60,24341.90,24360.40,0
1160094,2026-04-16 09:17:00+05:30,24360.90,24381.10,24360.90,24380.35,0
1160095,2026-04-16 09:18:00+05:30,24379.25,24379.25,24364.60,24376.20,0
1160096,2026-04-16 09:19:00+05:30,24373.05,24390.55,24373.05,24390.55,0
...,...,...,...,...,...,...
1743508,2026-04-16 15:25:00+05:30,24196.10,24199.95,24189.20,24193.15,0
1743509,2026-04-16 15:26:00+05:30,24193.15,24196.65,24190.10,24194.05,0
1743510,2026-04-16 15:27:00+05:30,24194.05,24195.40,24191.00,24192.80,0
1743511,2026-04-16 15:28:00+05:30,24192.80,24194.70,24185.15,24187.50,0
1743512,2026-04-16 15:29:00+05:30,24187.50,24190.45,24178.85,24188.40,0

In [35]:
file_path

WindowsPath('assets/logs/16APR2026/nifty_1min_16APR2026.xlsx')